"""
SymPy for Group Theory (Abstract Algebra)
===========================================
Demonstrates permutation groups, group operations, cycle notation,
order of elements, and group properties.

Relevant domain: Algebra > Abstract Algebra > Group Theory
"""

from sympy.combinatorics import Permutation, PermutationGroup
from sympy.combinatorics.named_groups import (SymmetricGroup, AlternatingGroup,
                                                CyclicGroup, DihedralGroup)

# ---------------------------------------------------------------------------
# Example 1: Permutations
# ---------------------------------------------------------------------------

print("=== Permutations ===")

# Create permutation in cycle notation
p1 = Permutation([1, 2, 0, 3])  # (0 1 2)(3) in one-line notation
p2 = Permutation([[0, 1, 2]])    # Cycle notation: (0 1 2)

print(f"p1 = {p1}")
print(f"p2 = {p2}")
print(f"p1 in cycle notation: {p1.cyclic_form}")
print(f"p1 in array form: {p1.array_form}")

# Composition
p3 = p1 * p2
print(f"\np1 * p2 = {p3}")
print(f"p2 * p1 = {p2 * p1}")
print(f"Commutative? {p1 * p2 == p2 * p1}")

# Inverse
print(f"\np1⁻¹ = {p1 ** -1}")
print(f"p1 * p1⁻¹ = {p1 * (p1 ** -1)}")

# Order of permutation
print(f"\nOrder of p1: {p1.order()}")
print(f"Is p1 even? {p1.is_even}")
print(f"Is p1 odd? {p1.is_odd}")

# ---------------------------------------------------------------------------
# Example 2: Symmetric Group S_n
# ---------------------------------------------------------------------------

print("\n=== Symmetric Group S_n ===")

S3 = SymmetricGroup(3)
print(f"S₃ order: {S3.order()}")
print(f"S₃ generators: {S3.generators}")
print(f"Is S₃ abelian? {S3.is_abelian}")

S4 = SymmetricGroup(4)
print(f"\nS₄ order: {S4.order()}")
print(f"Is S₄ abelian? {S4.is_abelian}")

# ---------------------------------------------------------------------------
# Example 3: Cyclic Group Z_n
# ---------------------------------------------------------------------------

print("\n=== Cyclic Group Z_n ===")

Z6 = CyclicGroup(6)
print(f"Z₆ order: {Z6.order()}")
print(f"Z₆ generators: {Z6.generators}")
print(f"Is Z₆ abelian? {Z6.is_abelian}")
print(f"Is Z₆ cyclic? {Z6.is_cyclic}")

# ---------------------------------------------------------------------------
# Example 4: Dihedral Group D_n
# ---------------------------------------------------------------------------

print("\n=== Dihedral Group D_n ===")

D4 = DihedralGroup(4)
print(f"D₄ order: {D4.order()}")
print(f"D₄ generators: {D4.generators}")
print(f"Is D₄ abelian? {D4.is_abelian}")

D3 = DihedralGroup(3)
print(f"\nD₃ order: {D3.order()}")
print(f"Is D₃ abelian? {D3.is_abelian}")

# ---------------------------------------------------------------------------
# Example 5: Alternating Group A_n
# ---------------------------------------------------------------------------

print("\n=== Alternating Group A_n ===")

A4 = AlternatingGroup(4)
print(f"A₄ order: {A4.order()}")
print(f"Is A₄ abelian? {A4.is_abelian}")
print(f"Is A₄ a subgroup of S₄? {S4.is_subgroup(A4) or A4.is_subgroup(S4)}")

# ---------------------------------------------------------------------------
# Example 6: Subgroups and Cosets
# ---------------------------------------------------------------------------

print("\n=== Subgroups ===")

S3 = SymmetricGroup(3)
# Generate a subgroup
H = PermutationGroup(Permutation([[0, 1]]))  # Subgroup generated by (0 1)
print(f"Subgroup H = <(0 1)>, order: {H.order()}")
print(f"Is H a subgroup of S₃? {H.is_subgroup(S3)}")

# Lagrange's theorem: order of subgroup divides order of group
print(f"Lagrange check: |S₃| / |H| = {S3.order()} / {H.order()} = {S3.order() // H.order()}")

# ---------------------------------------------------------------------------
# Example 7: Group Properties
# ---------------------------------------------------------------------------

print("\n=== Group Properties Summary ===")

groups = [
    ("Z₄", CyclicGroup(4)),
    ("Z₆", CyclicGroup(6)),
    ("S₃", SymmetricGroup(3)),
    ("S₄", SymmetricGroup(4)),
    ("D₃", DihedralGroup(3)),
    ("D₄", DihedralGroup(4)),
    ("A₄", AlternatingGroup(4)),
]

print(f"{'Group':<8} {'Order':<8} {'Abelian':<10} {'Cyclic':<10}")
print("-" * 36)
for name, G in groups:
    print(f"{name:<8} {str(G.order()):<8} {str(G.is_abelian):<10} {str(G.is_cyclic):<10}")
